name: Build and Push Docker Image to GitHub
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{secrets.USER}}
        password: ${{secrets.GH_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{secrets.USER}}/postal-patch:main
    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{secrets.USER}}/postal-patch:main
